In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a[2] = 10

In [8]:
a[2]

np.int64(10)

In [9]:
a

array([ 1,  2, 10,  4,  5])

In [10]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1,2,3,4],
    [4,5,6,5],
    [7,8,9,6]
])

In [14]:
n[0,1] = 20

In [15]:
n

array([[ 1, 20,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  6]])

In [16]:
n[2] = [1,1,1]

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [17]:
n

array([[ 1, 20,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  6]])

In [18]:
n[:,1]

array([20,  5,  8])

In [19]:
n[:,2] = [1,2,3]

In [20]:
n

array([[ 1, 20,  1,  4],
       [ 4,  5,  2,  5],
       [ 7,  8,  3,  6]])

In [21]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [22]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
b=10+(a*2)**2

In [26]:
b

array([10, 14, 26, 46, 74])

In [27]:
a+b

array([10, 15, 28, 49, 78])

In [28]:
a

array([0, 1, 2, 3, 4])

In [29]:
a>=2

array([False, False,  True,  True,  True])

In [30]:
b

array([10, 14, 26, 46, 74])

In [31]:
a>b

array([False, False, False, False, False])

In [32]:
a[a<b]

array([0, 1, 2, 3, 4])

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
a.min()

np.int64(0)

In [35]:
a.max()

np.int64(4)

In [36]:
a.sum()

np.int64(10)

In [37]:
a.mean()

np.float64(2.0)

In [38]:
a.std()

np.float64(1.4142135623730951)

In [39]:
u = np.array([2,4,5,6])

In [40]:
u

array([2, 4, 5, 6])

In [41]:
v = np.array([1,1,1,1])

In [42]:
v

array([1, 1, 1, 1])

In [43]:
u+v

array([3, 5, 6, 7])

In [44]:
u.shape

(4,)

In [45]:
def Vector_Vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i]*v[i]
        
    return result 

In [46]:
Vector_Vector_multiplication(u,v)

np.float64(17.0)

In [47]:
u.dot(v)

np.int64(17)

In [48]:
def Matrix_Vector_multiplication(n,v):
    assert n.shape[1] == v.shape[0]

    num_rows = n.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = np.dot(n[i],v)

    
    return result                           

In [49]:
Matrix_Vector_multiplication(n,v)

array([26., 16., 24.])

In [50]:
t = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8],
    [1,1,2]
])

In [51]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8],
       [1, 1, 2]])

In [52]:
def matrix_matrix_multiplication(n,t):
    assert n.shape[1] == t.shape[0]

    num_rows = n.shape[0]
    num_cols = t.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = t[:,i]
        nvi = Matrix_Vector_multiplication(n,vi)
        result[:,i] = nvi

    return result

In [53]:
matrix_matrix_multiplication(n,t)

array([[ 91., 113., 139.],
       [ 41.,  52.,  68.],
       [ 63.,  81., 105.]])

In [54]:
n.dot(t)

array([[ 91, 113, 139],
       [ 41,  52,  68],
       [ 63,  81, 105]])

In [55]:
I = np.eye(3)

In [56]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8],
       [1, 1, 2]])

In [58]:
t.dot(I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.],
       [1., 1., 2.]])

In [59]:
vs = t[[0,1,2]]
vs

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [60]:
vs_inv = np.linalg.inv(vs)
vs_inv

array([[ 4.50359963e+14, -1.12589991e+15,  6.75539944e+14],
       [-9.00719925e+14,  2.25179981e+15, -1.35107989e+15],
       [ 4.50359963e+14, -1.12589991e+15,  6.75539944e+14]])

In [62]:
vs_inv.dot(vs)

array([[ 0.25 , -0.125, -1.   ],
       [ 1.5  ,  2.25 ,  2.   ],
       [ 0.   ,  0.75 ,  1.   ]])